sudo: false
cache: pip

language: python

python:
    - 3.6
env:
    - TOXENV=manifest
    - TOXENV=docs
    - TOXENV=readme

matrix:
    include:
        - python: 3.6
          env: TOXENV=py

before_install:
    - pip install codecov

install:
    - pip install tox

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov
