sudo: false
cache: pip

language: python

python:
    - 3.6
env:
    - TOXENV=manifest
    - TOXENV=docs
    - TOXENV=readme

matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36

install:
    - pip install tox

script:
    - tox
