sudo: false
cache: pip

language: python

python:
    - 3.6

matrix:
  include:
    - env: TOXENV=py
    - env: TOXENV=docs
    - env: TOXENV=manifest
    - env: TOXENV=rst-lint
    - env: TOXENV=flake8

install:
    - pip install tox codecov coverage

script:
    - tox

after_success:
    - tox -e coverage-report
    - codecov
